# Generated by Django 4.0 on 2021-12-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('work_count', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'File - History',
                'verbose_name_plural': 'Files - History',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietary_id', models.IntegerField(blank=True, null=True)),
                ('iswc', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contributors', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('music_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_file', to='repertoire.files')),
            ],
            options={
                'verbose_name': 'Music - Work',
                'verbose_name_plural': 'Music - Works',
            },
        ),
    ]
